export const taskConstants = {
    TASK_CREATE_REQUEST: "TASK_CREATE_REQUEST",
    TASK_CREATE_FAILURE: "TASK_CREATE_FAILURE",
    TASK_CREATE_SUCCESS: "TASK_CREATE_SUCCESS",

    TASK_READ_REQUEST: "TASK_READ_REQUEST",
    TASK_READ_FAILURE: "TASK_READ_FAILURE",
    TASK_READ_SUCCESS: "TASK_READ_SUCCESS",

    TASK_DELETE_REQUEST: "TASK_DELETE_REQUEST",
    TASK_DELETE_FAILURE: "TASK_DELETE_FAILURE",
    TASK_DELETE_SUCCESS: "TASK_DELETE_SUCCESS"
}